### ISSUE TITLE
Add (optimized) API for server file copying

### ISSUE THREAD

**Issue by itsWindows11** [tmds/Tmds.Ssh#239]
[SSH.NET](https://github.com/sshnet/SSH.NET) has a fast path for copying & moving files & directories by calling `SftpFile.MoveTo(string)` & the copy equivalent.

This can currently be polyfilled by opening a stream, writing to the target file, then optionally deleting the source if moving, which proves to be inefficient especially on slow networks since the bytes to write are streamed on the user's network when all the effort can be handled server side.

**Comment by tmds** [comment]
Does this provide what you are looking for:
```cs
SftpClient.RenameAsync(string oldpath, string newpath, CancellationToken cancellationToken = default);
```

**Comment by itsWindows11** [comment]
For moving files this works as expected, forgot about renaming across different paths.

This doesn't resolve the concern regarding copying though.

**Comment by tmds** [comment]
I don't think SSH.NET supports server-side copying? Does it?

**Comment by itsWindows11** [comment]
Sounds like it only supports copying when synchronizing directories.

There's this [draft spec](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-extensions-00) that I found though, only some servers seem to support it including [OpenSSH 9](https://man.openbsd.org/sftp#copy).

**Comment by tmds** [comment]
> There's this [draft spec](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-extensions-00) that I found though, some servers seem to support it including [OpenSSH 9](https://www.openssh.com/txt/release-9.0).

I know about this one. I'll use this issue to track implementing it with a fallback for servers that don't support it.

**Comment by tmds** [comment]
This is part of 0.7.0 which was just released on nuget.org.
