### ISSUE TITLE
Update test container image to use newer OpenSSH server.

### ISSUE THREAD

**Issue by tmds** [tmds/Tmds.Ssh#243]
I've tried changing to an OpenSSH 9 version by changing to the `centos:stream10-development` base image in https://github.com/tmds/Tmds.Ssh/pull/242.

This is working fine when running tests on my local machine, but in CI the server is failing to authenticate users. The issue seems to be related to PAM which refuses the key after it was accepted as an authorized_key by OpenSSH.

Failing log (from CI):

```
debug2: auth_check_authkeys_file: /home/testuser/.ssh/authorized_keys: processed 5/5 lines
debug1: restore_uid: 0/0
debug1: auth_activate_options: setting new authentication options
debug1: do_pam_account: called
debug2: do_pam_account: auth information in SSH_AUTH_INFO_0
Failed publickey for testuser from 10.0.2.100 port 40930 ssh2: RSA SHA256:zxjEf8ywcbncdGEflP4PXxrOp8YxAO/2WBL/Rq/+k5w
```

Working log (from local machine):
```
debug2: auth_check_authkeys_file: /home/testuser/.ssh/authorized_keys: processed 5/5 lines
debug1: restore_uid: 0/0
debug1: auth_activate_options: setting new authentication options
debug1: do_pam_account: called
debug2: do_pam_account: auth information in SSH_AUTH_INFO_0
Accepted publickey for testuser from 127.0.0.1 port 42834 ssh2: RSA SHA256:zxjEf8ywcbncdGEflP4PXxrOp8YxAO/2WBL/Rq/+k5w
```

@jborean93 fyi. If you have some inputs, feel free to chime in.

**Comment by Jakuje** [comment]
Discussed this in chat previously, but do you need PAM at all in your tests? If not, it might make sense to try with `UsePam no` in `sshd_config`.
We try to run most of the libssh tests without pam as we do not need complex user authentication and management (unless we test the pam authentication itself, but in that case, we are providing the test server with the test pam stack + pam_wrapper).

I see you are also using kerberos. I think recent kerberos version are using KCM by default in Fedora (and EL10?), which depend on sssd-kcm running. This works in normal systems, but might have issues in containers. I would probably try to investigate if there are some kerberos related logs somewhere in the test case, even though this does not explain the difference between CI and local runs.

**Comment by jborean93** [comment]
Can you share the logs with `DEBUG3`, there are a few extra logs that might indicate what is rejecting the pubkey.

**Comment by tmds** [comment]
Fixed by https://github.com/tmds/Tmds.Ssh/pull/242.
