### ISSUE TITLE
Support downloading to a Stream

### ISSUE THREAD

**Issue by yokrysty** [tmds/Tmds.Ssh#261]
please add the possibility to download file to a Stream
SSH.Net has this possibility, but is way to slow
i adapted your library locally adding this feature to test and is way faster
but it would be better to depend on a nuget package instead of managing it myself
let me know if you want me to make pull request with my adaptions for this use case

**Comment by tmds** [comment]
hi @yokrysty,

> add the possibility to download file to a Stream

That would be a good feature to have!

The public API should be something like:
```cs
class SftpClient
{
  ValueTask DownloadFileAsync(string remoteFilePath, Stream destination, CancellationToken cancellationToken = default);
```

> let me know if you want me to make pull request with my adaptions for this use case

Yes, please do. I'm making a release in a week or two. We can aim to include this.

In your PR, I assume the following code (including `CopyBuffer`) can be shared, so let's see if we can avoid duplication by moving it into a common method.

https://github.com/tmds/Tmds.Ssh/blob/ad9c9f4126624c06dcf122c2100ad87a0737f821/src/Tmds.Ssh/SftpChannel.cs#L1084-L1100

Currently, `CopyBuffer` is writing synchronously into the `Stream`. Let's continue to do this if the stream is a `FileStream` or a `MemoryStream`. Otherwise, call `WriteAsync` and pass in the `CancellationToken`.

**Comment by yokrysty** [comment]
you kinda confused me with using the WriteAsync and i want to be on a same page with you

i am sure it will not write async because of this:
https://github.com/tmds/Tmds.Ssh/blob/ad9c9f4126624c06dcf122c2100ad87a0737f821/src/Tmds.Ssh/SftpChannel.cs#L1132-L1136
i could not use that line when async but:
i personally didn't encountered any true async stream
i know that even if FileStream and MemoryStream have WriteAsync they are not true async
i tried to mock an in memory async Stream but i encountered a problem that i need to know the fileOffset, maybe you can point me to such a Stream

my adaptations were simple and they suit my needs:
i just took out the FileStream from the original download method into a new method

in SftpClient.cs added
```C#
public async ValueTask DownloadFileAsync(string remoteFilePath, Stream destination, CancellationToken cancellationToken = default)
{
    var channel = await GetChannelAsync(cancellationToken).ConfigureAwait(false);
    await channel.DownloadFileAsync(remoteFilePath, destination, null, null, true, cancellationToken);
}
```

in SftpChannel.cs changed:
```C#
public async ValueTask DownloadFileAsync(string remotePath, string localPath, long? length, bool overwrite, UnixFilePermissions? permissions, bool throwIfNotFound, CancellationToken cancellationToken)
{
    await using FileStream localFile = OpenFileStream(localPath, overwrite ? FileMode.Create : FileMode.CreateNew, FileAccess.Write, FileShare.None, permissions!.Value);
    await DownloadFileAsync(remotePath, localFile, length, permissions, throwIfNotFound, cancellationToken);
}

public async ValueTask DownloadFileAsync(string remotePath, Stream destination, long? length, UnixFilePermissions? permissions, bool throwIfNotFound, CancellationToken cancellationToken)
{
    // Call GetAttributesAsync in parallel with OpenFileAsync.
    // We don't need to pass the CancellationToken since GetAttributesAsync will complete before the awaited OpenFileAsync completes.
    ValueTask<FileEntryAttributes?> getAttributes = length == null || permissions == null ? GetAttributesAsync(remotePath, followLinks: true) : default;

    using SftpFile? remoteFile = await OpenFileAsync(remotePath, SftpOpenFlags.Open, FileAccess.Read, SftpClient.DefaultFileOpenOptions, cancellationToken).ConfigureAwait(false);
    if (remoteFile is null)
    {
        if (throwIfNotFound)
        {
            throw new SftpException(SftpError.NoSuchFile);
        }
        return;
    }

    if (length == null || permissions == null)
    {
        FileEntryAttributes? attributes = await getAttributes.ConfigureAwait(false);
        if (attributes is null) // unlikely
        {
            attributes = await remoteFile.GetAttributesAsync(cancellationToken).ConfigureAwait(false);
        }
        length = attributes.Length;
        permissions = attributes.Permissions;
    }

    ValueTask previous = default;

    CancellationTokenSource? breakLoop = length > 0 ? new() : null;

    int maxPayload = MaxReadPayload;
    for (long offset = 0; offset < length; offset += maxPayload)
    {
        Debug.Assert(breakLoop is not null);
        if (!breakLoop.IsCancellationRequested)
        {
            await s_downloadBufferSemaphore.WaitAsync(cancellationToken).ConfigureAwait(false);
            long remaining = length.Value - offset;
            previous = CopyBuffer(previous, offset, remaining > maxPayload ? maxPayload : (int)remaining);
        }
    }

    await previous.ConfigureAwait(false);

    await remoteFile.CloseAsync(cancellationToken).ConfigureAwait(false);
    
    return;

    async ValueTask CopyBuffer(ValueTask previousCopy, long fileOffset, int length)
    {
        byte[]? buffer = null;
        try
        {
            try
            {
                if (breakLoop.IsCancellationRequested)
                {
                    // previousCopy will throw.
                    return;
                }

                buffer = ArrayPool<byte>.Shared.Rent(length);
                int remaining = length;
                long position = fileOffset;
                do
                {
                    int bytesRead = await remoteFile.ReadAtAsync(buffer.AsMemory(length - remaining, remaining), position, cancellationToken).ConfigureAwait(false);
                    if (bytesRead == 0)
                    {
                        // Unexpected EOF.
                        throw new SftpException(SftpError.Eof);
                    }
                    position += bytesRead;
                    remaining -= bytesRead;
                } while (remaining > 0);
            }
            // Wait for the previous buffer to be written so we're writing sequentially to the file.
            finally
            {
                await previousCopy.ConfigureAwait(false);
            }

            destination.Write(buffer.AsSpan(0, length));
        }
        catch
        {
            breakLoop.Cancel();
            throw;
        }
        finally
        {
            if (buffer != null)
            {
                ArrayPool<byte>.Shared.Return(buffer);
            }
            s_downloadBufferSemaphore.Release();
        }
    }
}
```

**Comment by tmds** [comment]
> you kinda confused me with using the WriteAsync and i want to be on a same page with you

Ignore this for a moment. We'll tackle it on the PR.

> true async stream

For example: `NetworkStream` is a true async stream.

> await using FileStream localFile = OpenFileStream(localPath, overwrite ? FileMode.Create : FileMode.CreateNew, FileAccess.Write, FileShare.None, permissions!.Value);
    await DownloadFileAsync(remotePath, localFile, length, permissions, throwIfNotFound, cancellationToken);

I want to preserve the behavior of not creating a local file when the remote path does not exist. This would change that.

If you'd like to contribute this, can you create a PR? It is easier for me to give feedback.

If you prefer I look into the implementation, that is also fine. Let me know.

**Comment by yokrysty** [comment]
> I want to preserve the behavior of not creating a local file when the remote path does not exist. This would change that.

ah i see, fair enough, i will try other approach
> If you'd like to contribute this, can you create a PR? It is easier for me to give feedback.
> If you prefer I look into the implementation, that is also fine. Let me know.

i will prepare a PR
