### ISSUE TITLE
Support "none"  authentication method

### ISSUE THREAD

**Issue by pkudrel** [tmds/Tmds.Ssh#265]
Hi, 
I'm trying to use `Tmdb.Ssh` with Tailscale SSH
https://tailscale.com/kb/1193/tailscale-ssh

So far no success due to lack of authentication method `none`.
It would be great if `Tmdb.Ssh` supported this feature

**Comment by tmds** [comment]
hi @pkudrel,

Authentication methods are represented through credential derived classes.

The API for `none` would be something like:
```cs
class NoCredential : Credential
{ }
```

I'm planning a release for the end of next week and I'll look into including this.

If you'd want to contribute this, let me know, and I can provide you some pointers.

**Comment by pkudrel** [comment]
I can take a look, but I must warn you that my knowledge of how the SSH protocol works at a low level is close to zero.

Besides of adding `class NoCredential : Credential;` I think there is need to refactor `SshSession.AuthenticateAsync` (not only because of the `NoCredential` case)

test

```csharp
 var s = new SshClientSettings { HostName = "sg1", UserName = "pkudrel" };
 using var client = new SshClient(s, _loggerFactory);
 using var process = await client.ExecuteAsync("uname -a");
```

log

```text
...

2024-12-09 08:56:45.245|TRC|Tmds.Ssh.SshClient|Sending SSH_MSG_USERAUTH_REQUEST 
3200000007706b756472656c0000000e7373682d636f6e6e656374696f6e0000  |2....pkudrel....ssh-connection..|
000f6773736170692d776974682d6d6963000000010000000b06092a864886f7  |..gssapi-with-mic..........*.H..|
12010202                                                          |....|
2024-12-09 08:56:45.280|TRC|Tmds.Ssh.SshClient|Received SSH_MSG_USERAUTH_FAILURE 
33000000097461696c7363616c6500                                    |3....tailscale.|
2024-12-09 08:56:45.283|INF|Tmds.Ssh.SshClient|Auth gssapi-with-mic method failed, continue with: tailscale
2024-12-09 08:56:45.286|ERR|Tmds.Ssh.SshClient|Could not connect to 'sg1' port 22The connection could not be established - AuthenticationFailed - Authentication failed.
```

From what I understand from this log, the Tailscale server is sending information that the only available method is `tailscale`, so the current implementation of `SshSession.AuthenticateAsync` will not work.

**Comment by tmds** [comment]
>  only available method is tailscale

That would be a `tailscale` specific mechanism, which is different than `none`.

What happens when you use the OpenSSH `ssh` command. If you add the `-v` option, you'll see some logging. Can it authenticate? What method does it use?

PS: don't share trace level logging (https://github.com/tmds/Tmds.Ssh?tab=readme-ov-file#logging).

**Comment by tmds** [comment]
> https://tailscale.com/kb/1193/tailscale-ssh

I've read through this. My understanding is that when you enable SSH for a Tailscale host, it runs a MiTM SSH server that accepts `none` authentication from the Tailscale IP address.

When you have it working with the regular OpenSSH `ssh` command using `none`. It should work with `Tmds.Ssh` as well (once we've added support for `none`).

I'll look into adding support for the `none` method.

**Comment by pkudrel** [comment]
>  Can it authenticate? What method does it use?

```
debug1: kex_ext_info_check_ver: ping@openssh.com=<0>
debug1: SSH2_MSG_SERVICE_ACCEPT received Authenticated to sg1 ([REDACTED]:22) using "none".
```

but there's no line similar to
```
debug1: Authentications that can continue: publickey,password
```

> That would be a tailscale specific mechanism, which is different than none.

That's for sure. But `none` shouldn't be listed at all:

https://datatracker.ietf.org/doc/html/rfc4252#section-4

**Comment by tmds** [comment]
Thanks, this is useful information!

> but there's no line similar to

I think the `ssh` client may start by trying `none` and then when that fails it knows what other methods to try. In this case, `none` worked, so the line of `Authentications that can continue` is not printed.

I'll give you a ping when this is implemented, so you can try it against Tailscale SSH with a NuGet package from the CI feed. Then it can be part of next week's release.

**Comment by tmds** [comment]
@pkudrel this is implemented. Can you give it a try against the Tailscale SSH using a NuGet package from the CI feed: https://github.com/tmds/Tmds.Ssh?tab=readme-ov-file#ci-feed.

**Comment by pkudrel** [comment]
Everything is working perfectly now! 
I truly appreciate your swift action - thank you!

**Comment by tmds** [comment]
This is part of 0.9.0 which was just uploaded to nuget.org.
