### ISSUE TITLE
Support uploading from a Stream

### ISSUE THREAD

**Issue by yokrysty** [tmds/Tmds.Ssh#267]
title is self explanatory, the counterpart of #261

**Comment by tmds** [comment]
API:
```cs
class SftpClient
{
  ValueTask UploadFileAsync(Stream source, string remoteFilePath, CancellationToken cancellationToken);
  ValueTask UploadFileAsync(Stream source, string remoteFilePath, bool overwrite = false, UnixFilePermissions? createPermissions = null, CancellationToken cancellationToken = default);
```

**Comment by yokrysty** [comment]
you can check what i did before the doing a PR, since i am not sure it's the way you wanted

**Comment by tmds** [comment]
hi @yokrysty, I took a look and I'd like to do it a bit differently. I'm going to tackle this one myself and I'll cc you on the PR so you can take a look and give feedback if you want.

**Comment by tmds** [comment]
This is part of 0.9.0 which was just uploaded to nuget.org.
