### ISSUE TITLE
API review

### ISSUE THREAD

**Issue by tmds** [tmds/Tmds.Ssh#89]
@scalablecory @antonfirsov @adamsitnik if you have an interest and some time, I'd love to get your feedback on the API of this library.

```cs
namespace Tmds.Ssh
{
class SshClient : IDisposable
{
  SshClient(string destination, Action<SshClientSettings>? configure = null) { }
  SshClient(SshClientSettings clientSettings) { }

  Task ConnectAsync(CancellationToken cancellationToken) { }

  Task<RemoteProcess> ExecuteAsync(string command, CancellationToken cancellationToken) { }
  Task<RemoteProcess> ExecuteAsync(string command, Action<ExecuteOptions>? configure = null, CancellationToken cancellationToken = default) { }

  Task<SshDataStream> OpenTcpConnectionAsync(string host, int port, CancellationToken cancellationToken = default);
  Task<SshDataStream> OpenUnixConnectionAsync(string path, CancellationToken cancellationToken = default);
}
class ExecuteOptions
{
  Encoding StandardInputEncoding { get; set; }
  Encoding StandardErrorEncoding { get; set; }
  Encoding StandardOutputEncoding { get; set; }
}
class RemoteProcess : IDisposable
{
  // Read from the remote process.
  ValueTask<(bool isError, string? line)> ReadLineAsync(bool readStdout = true, bool readStderr = true, CancellationToken cancellationToken = default) { }
  ValueTask<(string? stdout, string? stderr)> ReadToEndAsStringAsync(bool readStdout = true, bool readStderr = true, CancellationToken cancellationToken = default) { }
  IAsyncEnumerable<(bool isError, string line)> ReadAllLinesAsync(bool readStdout = true, bool readStderr = true, CancellationToken cancellationToken = default) { }
  ValueTask? ReadToEndAsync(Stream? stdoutStream, Stream? stderrStream, bool? disposeStreams, CancellationToken? cancellationToken) { }
  ValueTask<(bool isError, int bytesRead)> ReadAsync(Memory<byte>? stdoutBuffer, Memory<byte>? stderrBuffer, CancellationToken cancellationToken = default) { }
  ValueTask? ReadToEndAsync(Func<Memory<byte>, object, CancellationToken, ValueTask> handleStdout, object? stdoutContext, Func<Memory<byte>, object, CancellationToken, ValueTask> handleStderr, object? stderrContext, CancellationToken? cancellationToken) { }

  // Write to the remote process.
  ValueTask WriteAsync(ReadOnlyMemory<byte> buffer, CancellationToken cancellationToken = default) { }
  Task WriteAsync(ReadOnlyMemory<char> buffer, CancellationToken cancellationToken = default) { }
  Task WriteAsync(string value, CancellationToken cancellationToken = default) { }
  Task WriteLineAsync(ReadOnlyMemory<char> buffer, CancellationToken cancellationToken = default) { }
  Task WriteLineAsync(string? value, CancellationToken cancellationToken = default) { }
  Stream StandardInputStream { get; }
  StreamWriter StandardInputWriter { get; }

  // Wait for the remote process to exit.
  ValueTask WaitForExitAsync(CancellationToken cancellationToken) { }

  // CancellationToken that cancels when remote process terminates.
  CancellationToken ExecutionAborted { get; }

  // Exit code.
  int ExitCode { get; }
}
class SshDataStream : Stream
{
  CancellationToken StreamAborted { get; }
}
class SshClientSettings
{
  SshClientSettings() { }
  string? KnownHostsFile { get; set; }
  TimeSpan ConnectTimeout { get; set; }
  string UserName { get; set; }
  string Host { get; set; }
  int Port { get; set; }
  List<Credential> Credentials { get; }
  bool CheckGlobalKnownHostsFile { get; set; }
  KeyVerification? KeyVerification { get; set; }
}
class PublicKey
{
  ReadOnlyMemory<byte> SHA256Hash { get; }
}
enum KeyVerificationResult
{
  Trusted,
  AddKnownHost,
  Revoked,
  Error,
  Changed,
  Unknown,
}
delegate ValueTask<KeyVerificationResult> KeyVerification(KeyVerificationResult knownHostResult, SshConnectionInfo connectionInfo, CancellationToken cancellationToken);
class SshConnectionInfo
{
  PublicKey ServerKey { get; }
  string Host { get; }
  int Port { get; }
}
// Base class for all credentials.
abstract class Credential
{ }
class PrivateKeyFileCredential : Credential
{
  PrivateKeyFileCredential(string filename) { }
  string FileName { get; }
}
// Base class.
class SshException : Exception
{ }
// Operation on SshClient failed.
class SshOperationException : SshException
{ }
// SshClient encountered an error, connection is closed.
class SshSessionException : SshException
{ }
// Connection already closed. InnerException contains reason when closed due to failure.
class SshSessionClosedException : SshSessionException
{ }
}
```

**Comment by antonfirsov** [comment]
Two remarks:
- Can't all the `WriteAsync` methods return `ValueTask`, enabling a future optimization to get rid of `StreamWriter`'s task allocation?
- Why is the result of `ReadToEndAsync` nullable? Doesn't look like an easy thing to consume to me.

**Comment by tmds** [comment]
Thanks Anton for taking a look!

> Why is the result of ReadToEndAsync nullable? Doesn't look like an easy thing to consume to me.

I'm not sure how that got in there, this is a typo.

> Can't all the WriteAsync methods return ValueTask, enabling a future optimization to get rid of StreamWriter's task allocation?

Makes sense.
Maybe I should `ValueTask`all the methods, including those on `SshClient`?

**Comment by scalablecory** [comment]
For WaitForExitAsync and ExecutionAborted:

Two things to test for the same result? I would collapse into one.

WaitForExitAsync taking a cancellation token can be slightly confusing for users -- easy to confuse that it cancels the process rather than cancels the wait.

Consider using:

```c#
Task ProcessExited;
```

This will integrate well with the new WaitAsync method, and solve the cancellation token ambiguity.

```c#
await foo.ProcessExited.WaitAsync(cancellationToken);
// or
await foo.ProcessExited.WaitAsync(timeout: 1000);
```

**Comment by scalablecory** [comment]
Instead of having `Read` methods, consider just exposing a `Stream`/`StreamReader` for stdout. This would be more usable and also more consistent with how you're exposing stdin.

**Comment by scalablecory** [comment]
I'm not a huge fan of the methods taking `Action`. This pattern isn't super popular outside of ASP.NET, and seems like the overlap of this and ASP.NET code may be small -- might be more confusing than helpful.

**Comment by scalablecory** [comment]
`PrivateKeyFileCredential.FileName` -> `PrivateKeyFileCredential.FilePath`, assuming I'm understanding the use of it correctly.

**Comment by tmds** [comment]
@scalablecory thank you for making some time to give feedback!

> For WaitForExitAsync and ExecutionAborted: Two things to test for the same result? I would collapse into one.

They complete for similar reasons. One returns a `Task` to `await`, the other a `CancellationToken` to pass in

> This will integrate well with the new WaitAsync method, and solve the cancellation token ambiguity.

:+1: makes sense.

> Instead of having Read methods, consider just exposing a Stream/StreamReader for stdout. This would be more usable and also more consistent with how you're exposing stdin.

The APIs that are there make the user consume both standard output and standard error simultaneous. I see the value of having a separate `Stream`/`StreamReader`, though that makes the user only consume one.

Technically, SSH shares the same 'buffer' for both. So if you're ignoring one, it can fill up the buffer up to a point where you no longer receive the other. Though that probably doesn't happen much in practice.

> I'm not a huge fan of the methods taking Action. This pattern isn't super popular outside of ASP.NET, and seems like the overlap of this and ASP.NET code may be small -- might be more confusing than helpful.

For the constructor that takes a `destination` and an `Action` it serves the purpose of setting some values in the object based on the `destination`.

The `ExecuteAsync` method can change to take the `ExecuteOptions` directly.

> PrivateKeyFileCredential.FileName -> PrivateKeyFileCredential.FilePath, Same for KnownHostsFile.

I'll change these.

**Comment by tmds** [comment]
I have applied the various suggestions to the API.
